image: nightscape/scala-mill

stages:
  - compile
  - test

compile:
  stage: compile
  script:
    - timeout 3600 mill service.compile

test:
  stage: test
  script:
    - timeout 3600 mill service.test
