package models.daos

import models.{ Building, Classroom }
import scala.concurrent.Future

class BuildingDAOImpl {
//  def getAllRooms(building: Building): Future[Seq[Classroom]] = {
//
//  }
}

object BuildingDAOImpl {
    val data = Map(
//      "1202" -> Classroom(Building.fromString("1"), 2),
//      "1203" -> Classroom(Building.fromString("1"), 2),
//      "1204" -> Classroom(Building.fromString("1"), 2),
//      "1205" -> Classroom(Building.fromString("1"), 2),
//      "1206" -> Classroom(Building.fromString("1"), 2),
//      "1207" -> Classroom(Building.fromString("1"), 2),
//      "1208" -> Classroom(Building.fromString("1"), 2),
//      "1210" -> Classroom(Building.fromString("1"), 2),
//      "1211" -> Classroom(Building.fromString("1"), 2),
//      "1301" -> Classroom(Building.fromString("1"), 3),
//      "1302" -> Classroom(Building.fromString("1"), 3),
//      "1303" -> Classroom(Building.fromString("1"), 3),
//      "1304" -> Classroom(Building.fromString("1"), 3),
//      "1305" -> Classroom(Building.fromString("1"), 3),
//      "1306" -> Classroom(Building.fromString("1"), 3),
//      "1307" -> Classroom(Building.fromString("1"), 3),
//      "1308" -> Classroom(Building.fromString("1"), 3),
//      "1309" -> Classroom(Building.fromString("1"), 3),
//      "1310" -> Classroom(Building.fromString("1"), 3),
//      "1311" -> Classroom(Building.fromString("1"), 3),
//      "1401" -> Classroom(Building.fromString("1"), 4),
//      "1402" -> Classroom(Building.fromString("1"), 4),
//      "1403" -> Classroom(Building.fromString("1"), 4),
//      "1404" -> Classroom(Building.fromString("1"), 4),
//      "1405" -> Classroom(Building.fromString("1"), 4),
//      "1406" -> Classroom(Building.fromString("1"), 4),
//      "1407" -> Classroom(Building.fromString("1"), 4),
//      "1408" -> Classroom(Building.fromString("1"), 4),
//      "1409" -> Classroom(Building.fromString("1"), 4),
//      "1501" -> Classroom(Building.fromString("1"), 5),
//      "1502" -> Classroom(Building.fromString("1"), 5),
//      "1503" -> Classroom(Building.fromString("1"), 5),
//      "1504" -> Classroom(Building.fromString("1"), 5),
//      "1505" -> Classroom(Building.fromString("1"), 5),
//      "1506" -> Classroom(Building.fromString("1"), 5),
//      "1507" -> Classroom(Building.fromString("1"), 5),
//      "1508" -> Classroom(Building.fromString("1"), 5),
//      "1509" -> Classroom(Building.fromString("1"), 5),
//      "1601" -> Classroom(Building.fromString("1"), 6),
//      "1602" -> Classroom(Building.fromString("1"), 6),
//      "1603" -> Classroom(Building.fromString("1"), 6),
//      "1604" -> Classroom(Building.fromString("1"), 6),
//      "1605" -> Classroom(Building.fromString("1"), 6),
//      "1606" -> Classroom(Building.fromString("1"), 6),
//      "1607" -> Classroom(Building.fromString("1"), 6),
//      "1608" -> Classroom(Building.fromString("1"), 6),
//      "1609" -> Classroom(Building.fromString("1"), 6),
//      "2201" -> Classroom(Building.fromString("2"), 2),
//      "2202" -> Classroom(Building.fromString("2"), 2),
//      "2203" -> Classroom(Building.fromString("2"), 2),
//      "2204" -> Classroom(Building.fromString("2"), 2),
//      "2205" -> Classroom(Building.fromString("2"), 2),
//      "2207" -> Classroom(Building.fromString("2"), 2),
//      "2208" -> Classroom(Building.fromString("2"), 2),
//      "2210" -> Classroom(Building.fromString("2"), 2),
//      "2401" -> Classroom(Building.fromString("2"), 4),
//      "2402" -> Classroom(Building.fromString("2"), 4),
//      "2403" -> Classroom(Building.fromString("2"), 4),
//      "2404" -> Classroom(Building.fromString("2"), 4),
//      "2405" -> Classroom(Building.fromString("2"), 4),
//      "2407" -> Classroom(Building.fromString("2"), 4),
//      "2408" -> Classroom(Building.fromString("2"), 4),
//      "2409" -> Classroom(Building.fromString("2"), 4),
//      "2501" -> Classroom(Building.fromString("2"), 5),
//      "2502" -> Classroom(Building.fromString("2"), 5),
//      "2503" -> Classroom(Building.fromString("2"), 5),
//      "2504" -> Classroom(Building.fromString("2"), 5),
//      "2506" -> Classroom(Building.fromString("2"), 5),
//      "2507" -> Classroom(Building.fromString("2"), 5),
//      "2508" -> Classroom(Building.fromString("2"), 5),
//      "2509" -> Classroom(Building.fromString("2"), 5),
//      "3201" -> Classroom(Building.fromString("3"), 2),
//      "3203" -> Classroom(Building.fromString("3"), 2),
//      "3205" -> Classroom(Building.fromString("3"), 2),
//      "3206" -> Classroom(Building.fromString("3"), 2),
//      "3301" -> Classroom(Building.fromString("3"), 3),
//      "3302" -> Classroom(Building.fromString("3"), 3),
//      "3303" -> Classroom(Building.fromString("3"), 3),
//      "3304" -> Classroom(Building.fromString("3"), 3),
//      "3305" -> Classroom(Building.fromString("3"), 3),
//      "3306" -> Classroom(Building.fromString("3"), 3),
//      "3307" -> Classroom(Building.fromString("3"), 3),
//      "3308" -> Classroom(Building.fromString("3"), 3),
//      "3401" -> Classroom(Building.fromString("3"), 4),
//      "3402" -> Classroom(Building.fromString("3"), 4),
//      "3403" -> Classroom(Building.fromString("3"), 4),
//      "3404" -> Classroom(Building.fromString("3"), 4),
//      "3405" -> Classroom(Building.fromString("3"), 4),
//      "3406" -> Classroom(Building.fromString("3"), 4),
//      "3407" -> Classroom(Building.fromString("3"), 4),
//      "3408" -> Classroom(Building.fromString("3"), 4),
//      "3409" -> Classroom(Building.fromString("3"), 4),
//      "3501" -> Classroom(Building.fromString("3"), 5),
//      "3502" -> Classroom(Building.fromString("3"), 5),
//      "3503" -> Classroom(Building.fromString("3"), 5),
//      "3504" -> Classroom(Building.fromString("3"), 5),
//      "3505" -> Classroom(Building.fromString("3"), 5),
//      "3506" -> Classroom(Building.fromString("3"), 5),
//      "3507" -> Classroom(Building.fromString("3"), 5),
//      "3508" -> Classroom(Building.fromString("3"), 5),
//      "3509" -> Classroom(Building.fromString("3"), 5),
//      "C301" -> Classroom(Building.fromString("C"), 3),
//      "C302" -> Classroom(Building.fromString("C"), 3),
//      "C304" -> Classroom(Building.fromString("C"), 3),
//      "C305" -> Classroom(Building.fromString("C"), 3),
//      "C306" -> Classroom(Building.fromString("C"), 3),
//      "C307" -> Classroom(Building.fromString("C"), 3),
//      "C308" -> Classroom(Building.fromString("C"), 3),
//      "C309" -> Classroom(Building.fromString("C"), 3),
//      "C310" -> Classroom(Building.fromString("C"), 3),
//      "C311" -> Classroom(Building.fromString("C"), 3),
//      "C401" -> Classroom(Building.fromString("C"), 4),
//      "C402" -> Classroom(Building.fromString("C"), 4),
//      "C405" -> Classroom(Building.fromString("C"), 4),
//      "C406" -> Classroom(Building.fromString("C"), 4),
//      "C407" -> Classroom(Building.fromString("C"), 4),
//      "C408" -> Classroom(Building.fromString("C"), 4),
//      "C409" -> Classroom(Building.fromString("C"), 4),
//      "C410" -> Classroom(Building.fromString("C"), 4),
//      "C411" -> Classroom(Building.fromString("C"), 4),
//      "C412" -> Classroom(Building.fromString("C"), 4),
//      "C413" -> Classroom(Building.fromString("C"), 4),
//      "C501" -> Classroom(Building.fromString("C"), 5),
//      "C509" -> Classroom(Building.fromString("C"), 5),
//      "C510" -> Classroom(Building.fromString("C"), 5),
//      "C513" -> Classroom(Building.fromString("C"), 5),
//      "C514" -> Classroom(Building.fromString("C"), 5),
//      "C515" -> Classroom(Building.fromString("C"), 5),
//      "C606" -> Classroom(Building.fromString("C"), 6),
//      "C614" -> Classroom(Building.fromString("C"), 6),
//      "C615" -> Classroom(Building.fromString("C"), 6),
//      "C616" -> Classroom(Building.fromString("C"), 6)
    )
}
